
name: Docker Image CI

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  # Trigger the action manually from the UI
  workflow_dispatch:

jobs:

  build:
    name: buildnode
    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - uses: actions/checkout@v4
    - name: Build the Docker image hello
      run: docker build ./ --file ./Dockerfile --tag nodeapp:v1

    - uses: actions/checkout@v4
    - name: tag the Docker image hello
      run: docker image tag docker.io/library/hello:v1 astylacr.azurecr.io/nodeapp:v1
      
    - uses: actions/checkout@v4
    - name: push the Docker image hello
      run: docker push astylacr.azurecr.io/nodeapp:v1
      
