spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
  - hosts:
    - aksnginx.magpie.gr
    secretName: quickstart-example-tls
  rules:
  #- host: aksnginx.magpie.gr
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodelb
            port:
              number: 80
---
