apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodelb
            port:
              number: 80
      - path: /getdata
        pathType: Prefix
        backend:
          service:
            name: getdatalb
            port:
              number: 80
---