apiVersion: v1
kind: Service
metadata:
  name: nodelb
spec:
  ports:
  - port: 80
    targetPort: 3000
    #nodePort: 8088
  selector:
    app: nodeapp
  type:  ClusterIP # LoadBalancer #

---
